import type { Category, CategoryId, Group } from './types'

/**
 * The category registry. Adding a new kind of sensitive data is a matter of
 * adding an entry here plus a rule in one of the detector layers.
 */
const list: Category[] = [
  // --- personal -----------------------------------------------------------
  {
    id: 'PERSON',
    label: "Person's name",
    group: 'personal',
    severity: 'high',
    token: '[PERSON_NAME]',
    pseudoPrefix: 'Person',
    why: 'Names identify a real person and are the most common way customer data leaks into an AI tool.',
    priority: 50,
  },
  {
    id: 'EMAIL',
    label: 'Email address',
    group: 'personal',
    severity: 'high',
    token: '[EMAIL]',
    pseudoPrefix: 'Email',
    why: 'An email address identifies a person directly and often reveals the company they work for.',
    priority: 92,
  },
  {
    id: 'PHONE',
    label: 'Phone number',
    group: 'personal',
    severity: 'high',
    token: '[PHONE]',
    pseudoPrefix: 'Phone',
    why: 'Phone numbers are personal contact details and are rarely needed for an AI to help you.',
    priority: 80,
  },
  {
    id: 'NATIONAL_ID',
    label: 'ID or social security number',
    group: 'personal',
    severity: 'high',
    token: '[ID_NUMBER]',
    pseudoPrefix: 'IdNumber',
    why: 'Government ID numbers are highly sensitive personal data and are protected by law in most countries.',
    // Above payment cards: a 13-digit national ID is Luhn-valid, so when both
    // rules match the labelled identity number is the better reading.
    priority: 96,
  },
  {
    id: 'CREDIT_CARD',
    label: 'Payment card number',
    group: 'personal',
    severity: 'critical',
    token: '[CARD_NUMBER]',
    pseudoPrefix: 'Card',
    why: 'This looks like a real payment card number. It should never be pasted into an external tool.',
    priority: 95,
  },
  {
    id: 'BANK_ACCOUNT',
    label: 'Bank account number',
    group: 'personal',
    severity: 'critical',
    token: '[BANK_ACCOUNT]',
    pseudoPrefix: 'Account',
    why: 'Bank details can be used for fraud and are never required for an AI to answer a question.',
    priority: 94,
  },
  {
    id: 'POSTAL_ADDRESS',
    label: 'Street address',
    group: 'personal',
    severity: 'medium',
    token: '[ADDRESS]',
    pseudoPrefix: 'Address',
    why: 'A street address pinpoints where somebody lives or works.',
    priority: 55,
  },
  {
    id: 'LOCATION',
    label: 'Place name',
    group: 'personal',
    severity: 'low',
    token: '[LOCATION]',
    pseudoPrefix: 'Location',
    why: 'A place name can help identify the customer or site involved.',
    priority: 35,
  },
  {
    id: 'ORGANISATION',
    label: 'Company name',
    group: 'personal',
    severity: 'medium',
    token: '[COMPANY]',
    pseudoPrefix: 'Company',
    why: 'Naming the customer or partner tells an external AI tool exactly who you work with.',
    priority: 48,
  },

  // --- internal / business ------------------------------------------------
  {
    id: 'INTERNAL_HOST',
    label: 'Internal server name',
    group: 'internal',
    severity: 'medium',
    token: '[INTERNAL_SERVER]',
    pseudoPrefix: 'Server',
    why: 'Server and hostname naming reveals how your infrastructure is laid out.',
    priority: 68,
  },
  {
    id: 'IP_ADDRESS',
    label: 'IP address',
    group: 'internal',
    severity: 'medium',
    token: '[IP_ADDRESS]',
    pseudoPrefix: 'Ip',
    why: 'IP addresses map your network and can point an attacker at a specific machine.',
    priority: 82,
  },
  {
    id: 'MAC_ADDRESS',
    label: 'Hardware address',
    group: 'internal',
    severity: 'low',
    token: '[MAC_ADDRESS]',
    pseudoPrefix: 'Mac',
    why: 'A hardware address uniquely identifies one physical device.',
    priority: 81,
  },
  {
    id: 'NETWORK_PATH',
    label: 'Network share or path',
    group: 'internal',
    severity: 'medium',
    token: '[NETWORK_PATH]',
    pseudoPrefix: 'Path',
    why: 'File share paths expose internal server names and folder structure.',
    priority: 70,
  },
  {
    id: 'URL',
    label: 'Web link',
    group: 'internal',
    severity: 'low',
    token: '[URL]',
    pseudoPrefix: 'Link',
    why: 'Links can contain internal systems, tenant names or one-time access tokens.',
    priority: 60,
  },
  {
    id: 'CUSTOMER_ID',
    label: 'Customer number',
    group: 'internal',
    severity: 'medium',
    token: '[CUSTOMER_ID]',
    pseudoPrefix: 'Customer',
    why: 'A customer number ties the request back to a specific account in your systems.',
    priority: 74,
  },
  {
    id: 'CASE_ID',
    label: 'Support case number',
    group: 'internal',
    severity: 'medium',
    token: '[CASE_ID]',
    pseudoPrefix: 'Case',
    why: 'Case numbers link the text to a real support ticket and the customer behind it.',
    priority: 73,
  },
  {
    id: 'CONTRACT_ID',
    label: 'Contract or order number',
    group: 'internal',
    severity: 'medium',
    token: '[CONTRACT_ID]',
    pseudoPrefix: 'Contract',
    why: 'Contract and order references are commercially sensitive.',
    priority: 72,
  },
  {
    id: 'EMPLOYEE_ID',
    label: 'Employee number',
    group: 'internal',
    severity: 'medium',
    token: '[EMPLOYEE_ID]',
    pseudoPrefix: 'Employee',
    why: 'Employee numbers identify a specific colleague in your HR systems.',
    priority: 71,
  },
  // --- company confidential / IP ------------------------------------------
  {
    id: 'PROJECT_CODE',
    label: 'Internal project name',
    group: 'confidential',
    severity: 'medium',
    token: '[PROJECT_NAME]',
    pseudoPrefix: 'Project',
    why: 'Internal project names are often confidential before launch.',
    priority: 52,
  },
  {
    id: 'RELEASE_PLAN',
    label: 'Unreleased plan or date',
    group: 'confidential',
    severity: 'medium',
    token: '[RELEASE_PLAN]',
    pseudoPrefix: 'Release',
    why: 'Release timing for something not yet announced is commercially sensitive.',
    priority: 54,
  },
  {
    id: 'PRICING_TERM',
    label: 'Pricing or margin detail',
    group: 'confidential',
    severity: 'medium',
    token: '[PRICING]',
    pseudoPrefix: 'Pricing',
    why: 'Discounts, margins and deal values are commercially sensitive.',
    priority: 56,
  },
  {
    id: 'LICENSE_KEY',
    label: 'Licence key',
    group: 'internal',
    severity: 'high',
    token: '[LICENCE_KEY]',
    pseudoPrefix: 'Licence',
    why: 'Licence keys are entitlements tied to a paying customer.',
    priority: 88,
  },
  {
    id: 'REFERENCE_ID',
    label: 'Internal reference',
    group: 'internal',
    severity: 'low',
    token: '[REFERENCE]',
    pseudoPrefix: 'Ref',
    why: 'This looks like an internal reference code from one of your systems.',
    priority: 40,
  },
  {
    id: 'UUID',
    label: 'System identifier',
    group: 'internal',
    severity: 'low',
    token: '[SYSTEM_ID]',
    pseudoPrefix: 'SystemId',
    why: 'Unique system IDs can be traced back to a specific object in your environment.',
    priority: 84,
  },

  // --- secrets ------------------------------------------------------------
  {
    id: 'API_KEY',
    label: 'API key',
    group: 'secret',
    severity: 'critical',
    token: '[REMOVED_SECRET]',
    pseudoPrefix: 'Secret',
    why: 'This is a live credential. Anyone who sees it can use it. Rotate it if it has already been shared.',
    priority: 100,
  },
  {
    id: 'PASSWORD',
    label: 'Password',
    group: 'secret',
    severity: 'critical',
    token: '[REMOVED_SECRET]',
    pseudoPrefix: 'Secret',
    why: 'A password in plain text is the highest-risk thing you can paste into an external tool.',
    priority: 100,
  },
  {
    id: 'ACCESS_TOKEN',
    label: 'Access token',
    group: 'secret',
    severity: 'critical',
    token: '[REMOVED_SECRET]',
    pseudoPrefix: 'Secret',
    why: 'Tokens grant access to systems on your behalf until they expire or are revoked.',
    priority: 100,
  },
  {
    id: 'PRIVATE_KEY',
    label: 'Private key',
    group: 'secret',
    severity: 'critical',
    token: '[REMOVED_SECRET]',
    pseudoPrefix: 'Secret',
    why: 'A private key is the master credential for a server or certificate.',
    priority: 100,
  },
  {
    id: 'CONNECTION_STRING',
    label: 'Database connection',
    group: 'secret',
    severity: 'critical',
    token: '[REMOVED_SECRET]',
    pseudoPrefix: 'Secret',
    why: 'Connection strings usually embed a username and password for a live database.',
    priority: 99,
  },
]

export const CATEGORIES: Record<CategoryId, Category> = Object.fromEntries(
  list.map((c) => [c.id, c]),
) as Record<CategoryId, Category>

export function category(id: CategoryId): Category {
  return CATEGORIES[id]
}

export const GROUP_META: Record<
  Group,
  { label: string; singular: string; blurb: string; color: string }
> = {
  personal: {
    label: 'personal details',
    singular: 'personal detail',
    blurb: 'Names, contact details and anything that points at a real person.',
    color: 'var(--risk-high)',
  },
  internal: {
    label: 'internal details',
    singular: 'internal detail',
    blurb: 'Server names, customer numbers and other things specific to your company.',
    color: 'var(--risk-medium)',
  },
  confidential: {
    label: 'business-sensitive details',
    singular: 'business-sensitive detail',
    blurb: 'Roadmaps, pricing and internal plans that should stay inside the company.',
    color: 'var(--risk-business)',
  },
  secret: {
    label: 'possible secrets',
    singular: 'possible secret',
    blurb: 'Passwords, keys and tokens. These are always removed completely.',
    color: 'var(--risk-critical)',
  },
}

export const GROUP_ORDER: Group[] = [
  'secret',
  'personal',
  'confidential',
  'internal',
]
